parts<-read.csv("../Data/warrantyClaimParts",as.is=TRUE)
dim(parts)
part_names <-c("CLM_SRVC_PART_ID","CLM_SRVC_ID","PREAUTH_REF","PART_STR_CD","PART_STR_NM","IS_SRVC_PART_RPLC","PART_ITEM_CLS_ID","PART_ITEM_CD","PART_ITEM_ID"
               ,"PART_ITEM_SRL","PART_ITEM_UOM_CD","PART_ITEM_QTY","PART_ITEM_UNITAMT","PART_ITEM_ORGNLAMT","PART_ITEM_REQAMT","PART_ITEM_ADJPCT","PART_ITEM_ADJAMT"
               ,"PART_ITEM_TTLAMT","IS_RETURNABLE","CREATED_BY_USER","UPDATED_BY_USER","CREATED_BY_APPLN","UPDATED_BY_APPLN","CREATED_DT","UPDATED_DT","PART_TYPE"
               ,"PART_ORDR_CD","PART_FLWUP_CD","PART_ITEM_ADJQTY","PART_ITEM_ADJUOM","PART_ITEM_ADJPRC","PART_ITEM_UNITCST","PART_ITEM_TTLCST","PART_SUPP_ID"
               ,"SUPP_PART_ID","SUPP_PART_CD","PART_ITEM_SHIP_TYP","PART_ITEM_STATUS","PART_UNIT_CORE","PART_TTL_CORE","PART_RET_QTY","PART_INV_REF","IS_PART_SHIP"
               ,"PART_ITEM_SRL_OLD","PART_ITEM_STRDCOST","ITEM","SUBSYSTEM","SOURCE")

